### ISSUE TITLE
Unable to Analyze two surfaces together

### ISSUE THREAD

**Issue by Vchadha2** [ContactEngineering/topobank#962]
Hello, I am unable to analyze two surfaces together and it gives me a server error.
I am attaching a screenshot of the error. 
I tried multiple different surfaces to make sure the issue was not my surface. Plus I am able to analyze a surface individually but not multiple together.

<img width="839" alt="Screenshot 2023-01-31 131641" src="https://user-images.githubusercontent.com/95500485/215848141-d99f7168-9daa-48c8-ab71-d3b29dca0b08.png">

**Comment by pastewka** [comment]
Hi @Vchadha2 - Thanks for reporting. We pushed an update today that must have broken this. I won't manage to fix it today but will look tomorrow.

**Comment by Vchadha2** [comment]
@pastewka Thank you!

**Comment by Vchadha2** [comment]
Hey @pastewka I see you fixed the issue, but I am still getting the same error

**Comment by pastewka** [comment]
It's not yet deployed, working in it now.

**Comment by pastewka** [comment]
@Vchadha2 - I just deployed the fix. Can you try again if it works now?

**Comment by Vchadha2** [comment]
@pastewka Yes I just tried it works

**Comment by pastewka** [comment]
Perfect!
